### ISSUE TITLE
Ability to override arguments in git init/clone

### ISSUE THREAD

**Issue by jyaworski** [theforeman/puppet-git#19]
Hello:

Looking at https://github.com/theforeman/puppet-git/blob/master/manifests/repo.pp I don't see a way to set, for example, core.sharedrepository. Can we have the ability to set params on init/clone as part of the defined type?

**Comment by ekohl** [comment]
As you correctly spotted, this is currently not possible. If you can come with a pull request, that would be great. Otherwise it would be helpful to know what you'd expect. Do you set it using command line parameters during clone/init or after the initial clone/init using ```git config```?

**Comment by jyaworski** [comment]
Please see #20.
