### ISSUE TITLE
git::repo usage example and definition don't match - I can't clone a repo right now

### ISSUE THREAD

**Issue by dgoldsmith** [theforeman/puppet-git#50]
I am currently using release 4.0.0 of the module.

From the manifests/repo.pp file, here are the comments about the define params, example usage and the actual define param definitions.

```puppet
== Parameters:
#
# $target::   Target folder. Required.
#
# $bare::     Create a bare repository. Defaults to false.
#
# $source::   Source to clone from. If not specified, no remote will be used.
#
# $user::     Owner of the repository. Defaults to root.
#
# $group::    Group of the repository. Defaults to root.
#
# $mode::     Mode of the repository root. Defaults to 0755.
#
# $workdir::  The working directory while executing git
#
# $args::     Optional arguments to the git command
#
# $bin::      Git binary
#
# == Usage:
#
#   git::repo {'mygit':
#     target => '/home/user/puppet-git',
#     source => 'git://github.com/theforeman/puppet-git.git',
#     user   => 'user',
#   }
#
define git::repo (
  String $target,
  Boolean $bare = false,
  Boolean $source = false,
  String $user = 'root',
  String $group = 'root',
  String $mode = '0755',
  Stdlib::Absolutepath $workdir = '/tmp',
  Optional[String] $args = undef,
  String $bin = $::git::bin,
) {
```

In the notes, $source is the URI/URL of the external repo.
In the example, $source is the URI/URL of the external repo.
In the define declaration, $source is a boolean -- Puppet 5.x does not like a String value here.

When was $source changed from a String to a Boolean?

Looking thru the define code:
```puppet
  $args_real = $bare ? {
    true    => "${args} --bare",
    false   => $args,
  }

  if $source {
    $cmd = "${bin} clone ${args_real} --recursive ${source} ${target}"
  } else {
    $cmd = "${bin} init ${args_real} ${target}"
  }
```
So, if $bare => true, $source => true and $args is 'https://github.com/PaloAltoNetworks/minemeld-ansible.git' and $target is '/root/minemeld-ansible'

So if my define call looks like:
```puppet
  git::repo { 'minemeld-ansible':
    args   => 'https://github.com/PaloAltoNetworks/minemeld-ansible.git',
    source => true,
    target => '/root/minemeld-ansible',
  }
```
then:

$bare defaults to false
$args_real is set to 'https://github.com/PaloAltoNetworks/minemeld-ansible.git'
$cmd is set to '/usr/bin/git clone https://github.com/PaloAltoNetworks/minemeld-ansible.git --recursive true /root/minemeld-ansible'

and this command fails to execute.

If I get rid of 'true' in the string, then the command succeeds.

Here is info about the system:

[root@p-1-tis-mgr-1b test]# cat /etc/redhat-release
CentOS Linux release 7.5.1804 (Core)
[root@p-1-tis-mgr-1b test]# rpm -qa | grep ^git
git-1.8.3.1-20.el7.x86_64

Is no one else affected by this?

If I look at the latest version of the foreman/git module, its still the same so updating to the latest 4.1.1 release will not appear to solve this issue.

Should the foreman/git module be able to be used to configure any git repo or is it tied more directly just to use with the Foreman project?  I cannot currently use puppetlabs/git because we have a Foreman server and it requires the foreman/git module.

Thanks,
David Goldsmith

**Comment by ekohl** [comment]
You're right, this can never have worked and is broken since 3.0.0. Taking a look

**Comment by dgoldsmith** [comment]
Looks like the parameter was treated implicitly as a boolean before then, but the 3.0.0 release was when the explicit Boolean type was applied to the define param, and the module was updated to force Puppet 4.6.1. as a minimum, so the type enforcement started at that time.

Thanks for looking at it.

**Comment by ekohl** [comment]
I've opened https://github.com/theforeman/puppet-git/pull/51 which I think fixes it.
