### ISSUE TITLE
Switch to `vcsrepo`

### ISSUE THREAD

**Issue by jcpunk** [theforeman/puppet-git#90]
Would it make sense to have the `git::repo` use the `vcsrepo` type rather than the custom exec logic?

**Comment by ekohl** [comment]
I'm not against that, but then I wonder if we shouldn't retire the module completely. I can't find if `vcsrepo` actually ensures the package is installed.

**Comment by jcpunk** [comment]
Alas, `vcsrepo` doesn't install packages.  So having some sort of assurance that `git` is actually present is probably a good thing.

**Comment by ekohl** [comment]
Perhaps a `vcsrepo::install::git` (or similar) would make sense then? The `vcsrepo` should also autorequire the package so you don't have to manually take care of that every time you use the `vcsrepo` type.

**Comment by jcpunk** [comment]
That would be neat!

**Comment by jcpunk** [comment]
Based on your idea I built up https://github.com/puppetlabs/puppetlabs-vcsrepo/pull/586

**Comment by ekohl** [comment]
Now that https://github.com/theforeman/puppet-puppet/pull/860 has been merged we no longer have a need for this module. I'd like to deprecate it and stop maintaining it.

We should do so when all Foreman versions that use this module have gone out of support.

Thanks for your effort!
